name: Release Helm chart

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
#    outputs:
#      ttt:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: biointelligence/evolution-of-moths
          tags: latest
          tag_with_sha: true
