name: Release

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        id: build-push
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: biointelligence/evolution-of-moths
          cache_froms: biointelligence/evolution-of-moths:latest
          tags: latest
          tag_with_sha: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull biointelligence/evolution-of-moths:latest
            docker stop evm
            docker rm evm
            docker run -e JAVA_OPTS=’-Xms512M -Xmx512M -XX:PermSize=256m -XX:MaxPermSize=256m’ --name=evm --restart=always -p 80:2000 -d biointelligence/evolution-of-moths:latest
